"""Project paths and analysis constants.

Every path is derived from this file's location, so nothing is hardcoded to
a machine. Modules import from here instead of building their own paths.
"""

from __future__ import annotations

from pathlib import Path

# src/routeiq/config.py -> project root is two levels above the package.
PROJECT_ROOT: Path = Path(__file__).resolve().parents[2]

# --- Data ---------------------------------------------------------------
DATA_DIR: Path = PROJECT_ROOT / "data"
RAW_DATA_DIR: Path = DATA_DIR / "raw"
PROCESSED_DATA_DIR: Path = DATA_DIR / "processed"
CLEANED_DATA_DIR: Path = PROCESSED_DATA_DIR  # legacy alias used by the Phase 1 pipeline

# Raw Kaggle file: not redistributed, download it into data/raw/ (see data/README.md).
RAW_DATA_CSV: Path = RAW_DATA_DIR / "amazon_delivery.csv"
SOURCE_RAW_CSV: Path = PROJECT_ROOT / "amazon_delivery.csv"  # optional legacy location

CLEANED_DELIVERY_CSV: Path = PROCESSED_DATA_DIR / "cleaned_delivery.csv"
SLA_REFERENCE_CSV: Path = PROCESSED_DATA_DIR / "sla_reference.csv"
ANALYTICAL_DATASET_CSV: Path = PROCESSED_DATA_DIR / "analytical_deliveries.csv"

# --- Outputs (all regenerated by scripts/run_analysis.py) -----------------
OUTPUTS_DIR: Path = PROJECT_ROOT / "outputs"
TABLES_DIR: Path = OUTPUTS_DIR / "tables"
FIGURES_DIR: Path = OUTPUTS_DIR / "figures"
SQL_RESULTS_DIR: Path = OUTPUTS_DIR / "sql_results"
PIPELINE_REPORTS_DIR: Path = OUTPUTS_DIR / "pipeline_reports"
RESULTS_JSON: Path = OUTPUTS_DIR / "results.json"

REPORTS_DIR: Path = PIPELINE_REPORTS_DIR  # legacy alias
PROFILING_REPORT_MD: Path = PIPELINE_REPORTS_DIR / "profiling_report.md"
CLEANING_LOG_MD: Path = PIPELINE_REPORTS_DIR / "cleaning_log.md"
VALIDATION_REPORT_MD: Path = PIPELINE_REPORTS_DIR / "validation_report.md"

LOGS_DIR: Path = PROJECT_ROOT / "logs"
LOG_FILE_PREFIX: str = "routeiq"

# --- Analysis constants ---------------------------------------------------
EXPECTED_ROWS: int = 43_648            # rows in the cleaned dataset
SLA_PERCENTILE: float = 0.75           # analyst-defined benchmark (see docs/methodology.md)
SLA_SENSITIVITY_PERCENTILES: tuple[float, ...] = (0.70, 0.75, 0.80, 0.90)
RATING_THRESHOLD: float = 4.5          # data-driven step (docs/analytical_findings.md)
AGE_THRESHOLD: int = 30                # data-driven step
RANDOM_SEED: int = 42


def ensure_directory_structure() -> None:
    """Create output folders if missing. Never touches file contents."""
    for d in (PROCESSED_DATA_DIR, RAW_DATA_DIR, OUTPUTS_DIR, TABLES_DIR, FIGURES_DIR,
              SQL_RESULTS_DIR, PIPELINE_REPORTS_DIR, LOGS_DIR):
        d.mkdir(parents=True, exist_ok=True)
